FROM python:3.10-slim

WORKDIR /app

# Installer curl + MLflow
RUN apt-get update && apt-get install -y curl && \
    pip install --upgrade pip && \
    pip install mlflow==3.3.1 psycopg2-binary

EXPOSE 5000
