FROM python:3.11-slim

WORKDIR /app

# Copier uniquement requirements
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install mlflow==3.3.1 psycopg2-binary

# Copier uniquement le code nécessaire
COPY ./scripts ./scripts

EXPOSE 8501 8502

# Par défaut, rien n'est lancé : on le met dans docker-compose
CMD ["tail", "-f", "/dev/null"]

