version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-cde
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trustpilot
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo-cde
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: trustpilot
    ports:
      - "27017:27017"
    volumes:
      - ./docker-data/mongodb:/data/db
    command: --auth

  mlflow:
    image: ghcr.io/mlflow/mlflow:2.8.0
    container_name: mlflow-cde
    restart: unless-stopped
    environment:
      # Base MLflow stockée dans Postgres (⚠️ utilise "postgres" et pas "localhost")
      MLFLOW_TRACKING_URI: postgresql+psycopg2://admin:admin@postgres/mlflow_db
      # Dossier des artefacts à l'intérieur du container
      MLFLOW_ARTIFACT_ROOT: /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      # Persistance locale des artefacts
      - ./docker-data/mlflow:/mlflow/artifacts
    depends_on:
      - postgres

